# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
flutter_application_path = '/Users/ysidhernandez/Documents/Projects/Flutter/demo/Modulo/flutter_demo'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  # Pods for demo
install_all_flutter_pods(flutter_application_path)
end
